// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ChinookSystem.Entities
{
    [Index("ArtistId", Name = "IFK_AlbumsArtistId")]
    internal partial class Album
    {
        public Album()
        {
            Tracks = new HashSet<Track>();
        }
        //  This properties hold actual data from your database
        [Key]
        public int AlbumId { get; set; }
        [Required(ErrorMessage = "Album title is required")]
        [StringLength(160, ErrorMessage = "Album title is limited to 160 characters")]
        public string Title { get; set; }
        public int ArtistId { get; set; }
        public int ReleaseYear { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string ReleaseLabel { get; set; }

        //  These properties are your naviagational properties
        //  These properties do NOT hold "real" data
        //  These properties are only in "context" during the exection of your query
        [ForeignKey("ArtistId")]
        [InverseProperty("Albums")]
        public virtual Artist Artist { get; set; }
        [InverseProperty("Album")]
        public virtual ICollection<Track> Tracks { get; set; }
    }
}